const data = [
  {
    id: 1,
    title: "Cadeira Gamer",
    price: 899.99,
    description: "Cadeira ergonômica para jogos, com ajuste de altura e apoio lombar.",
    image: "/images/cadeira-gamer.jpg",
    tags: ["MÓVEL", "VENDIDO"],
  },
  {
    id: 2,
    title: "Notebook Dell Inspiron",
    price: 3499.90,
    description: "Notebook com processador i7, 16GB RAM e SSD 512GB.",
    image: "/images/notebook-dell.jpg",
    tags: ["ELETRÔNICO"],
  },
  {
    id: 3,
    title: "Caneca Personalizada",
    price: 29.99,
    description: "Caneca de porcelana com estampa exclusiva.",
    image: "/images/caneca.jpg",
    tags: ["PAPELARIA"],
  },
  {
    id: 4,
    title: "Luminária LED",
    price: 59.90,
    description: "Luminária de mesa com ajuste de intensidade e cor.",
    image: "/images/luminaria.jpg",
    tags: ["UTENSÍLIO"],
  },
  {
    id: 5,
    title: "Caderno Universitário",
    price: 19.90,
    description: "Caderno 200 folhas, capa dura, diversas estampas.",
    image: "/images/caderno.jpg",
    tags: ["PAPELARIA"],
  },
  {
    id: 6,
    title: "Smartphone Samsung Galaxy",
    price: 1999.00,
    description: "Smartphone com tela AMOLED, 128GB, câmera tripla.",
    image: "/images/smartphone.jpg",
    tags: ["ELETRÔNICO"],
  },
  {
    id: 7,
    title: "Kit Brinquedos Educativos",
    price: 89.90,
    description: "Kit com blocos de montar e jogos de lógica para crianças.",
    image: "/images/brinquedos.jpg",
    tags: ["BRINQUEDOS"],
  },
  {
    id: 8,
    title: "Mesa de Escritório",
    price: 499.90,
    description: "Mesa em MDF, 1,20m, ideal para home office.",
    image: "/images/mesa.jpg",
    tags: ["MÓVEL"],
  },
  {
    id: 9,
    title: "Fone de Ouvido Bluetooth",
    price: 149.90,
    description: "Fone sem fio com cancelamento de ruído.",
    image: "/images/fone.jpg",
    tags: ["ELETRÔNICO"],
  },
  {
    id: 10,
    title: "Livro: O Poder do Hábito",
    price: 39.90,
    description: "Livro best-seller sobre mudança de hábitos.",
    image: "/images/livro.jpg",
    tags: ["PAPELARIA"],
  },
  {
    id: 11,
    title: "Camiseta Básica",
    price: 49.90,
    description: "Camiseta 100% algodão, várias cores.",
    image: "/images/camiseta.jpg",
    tags: ["VESTUÁRIO"],
  },
  {
    id: 12,
    title: "Relógio de Parede Moderno",
    price: 79.90,
    description: "Relógio silencioso, design minimalista.",
    image: "/images/relogio.jpg",
    tags: ["UTENSÍLIO"],
  },
  {
    id: 13,
    title: "Kit Maquiagem Completo",
    price: 129.90,
    description: "Kit com sombras, batons e pincéis.",
    image: "/images/maquiagem.jpg",
    tags: ["SAUDE E BELEZA"],
  },
  {
    id: 14,
    title: "Tênis Esportivo",
    price: 199.90,
    description: "Tênis leve e confortável para corrida.",
    image: "/images/tenis.jpg",
    tags: ["VESTUÁRIO"],
  },
  {
    id: 15,
    title: "Aspirador de Pó Portátil",
    price: 249.90,
    description: "Aspirador compacto, ideal para carros e pequenos ambientes.",
    image: "/images/aspirador.jpg",
    tags: ["UTENSÍLIO"],
  },
  {
    id: 16,
    title: "Bloco de Notas Adesivas",
    price: 9.90,
    description: "Bloco com 100 folhas adesivas coloridas.",
    image: "/images/bloco-notas.jpg",
    tags: ["PAPELARIA"],
  },
  {
    id: 17,
    title: "Boneca de Pano",
    price: 59.90,
    description: "Boneca artesanal, feita à mão.",
    image: "/images/boneca.jpg",
    tags: ["BRINQUEDOS"],
  },
  {
    id: 18,
    title: "Kit Talheres Inox",
    price: 79.90,
    description: "Kit com 24 peças em aço inox.",
    image: "/images/talheres.jpg",
    tags: ["UTENSÍLIO"],
  },
  {
    id: 19,
    title: "Perfume Importado",
    price: 299.90,
    description: "Fragrância marcante, longa duração.",
    image: "/images/perfume.jpg",
    tags: ["SAUDE E BELEZA"],
  },
  {
    id: 20,
    title: "Carrinho de Controle Remoto",
    price: 149.90,
    description: "Carrinho elétrico, bateria recarregável.",
    image: "/images/carrinho.jpg",
    tags: ["BRINQUEDOS"],
  },
];

export default data;